#!/bin/bash
# box-alsa-setup.sh — pojmenuje zvuková zařízení podle typu a nastaví ALSA default.
#
#   pcm.usb      = USB zvuková karta boxu (AXAGON ADA-17) — hraje se do ní
#   pcm.builtin  = vestavěný jack Raspberry Pi (bcm2835 Headphones)
#   pcm.!default = usb, takže tracker/sampler nemusí nic přepínat
#
# Detekce karty:
#   USB karta = /sys/class/sound/cardN/device ukazuje do cesty s /usb, A MUSÍ
#               mít playback. Webkamera C920 je taky USB audio zařízení, ale má
#               jen capture — bez podmínky na playback by se vybrala ona.
#   builtin   = cesta pod /sys/devices/platform/ pro bcm2835-audio.
#
# Důležité, ověřeno na Boxu A:
#   * v definici pcm.se NESMÍ psát slovo device (device 0) — alsa-lib pak daný
#     pcm vůbec neregistruje a default je tím rozbitej.
#   * type plug, ne type hw: hw neumí přehrát mono (1 kanál) a aplay pak
#     skončí "Channels count non available".
#   * karta se odvolává JMENEM (hw:CARD=Adapter,DEV=0), ne číslem (hw:3,0).
#     USB zvukovka v boxu je na hubu a po přehození / restartu se číslo může
#     přehodit; jméno z /proc/asound/cardN/id zůstává, a tak pcm.ukazuje pořád
#     na kartu a ne na webkameru. ctl.!default jméno neumí, tam musí být číslo.
#
#   usage: sudo box-alsa-setup.sh
#
# Testovatelnost (viz tests/test-box-alsa-setup.sh): kořeny lze přesměrovat,
# aby se detekce dala pustit nad falešným stromem bez skutečného hardware.
# Výchozí hodnoty jsou přesně produkční cesty.
#   ABC38_SOUND_SYSFS  default /sys/class/sound
#   ABC38_ASOUND_PROC  default /proc/asound
#   ABC38_ASOUND_CONF  default /etc/asound.conf

set -e

SYSFS="${ABC38_SOUND_SYSFS:-/sys/class/sound}"
PROC="${ABC38_ASOUND_PROC:-/proc/asound}"
OUT="${ABC38_ASOUND_CONF:-/etc/asound.conf}"

USB_CARD=""
BUILTIN_CARD=""

card_id() {
    [ -r "$PROC/card$1/id" ] && cat "$PROC/card$1/id"
}

# pcm jméno pro kartu: "hw:CARD=<id>,DEV=0" pokud id známe, jinak "hw:<n>,0"
card_pcm() {
    local n="$1" id
    id="$(card_id "$n" || true)"
    if [ -n "$id" ]; then
        echo "hw:CARD=$id,DEV=0"
    else
        echo "hw:$n,0"
    fi
}

for dev in "$SYSFS"/card*; do
    n="${dev##*card}"
    case "$n" in "" | *[!0-9]*) continue ;; esac
    path="$(readlink -f "$dev/device" 2>/dev/null || true)"
    [ -n "$path" ] || continue
    case "$path" in
        */usb*)
            if [ -z "$USB_CARD" ] && ls "$PROC"/card$n/pcm*p >/dev/null 2>&1; then
                USB_CARD="$n"
            fi ;;
        */platform/*bcm2835-audio*)
            if [ -z "$BUILTIN_CARD" ]; then
                BUILTIN_CARD="$n"
            fi ;;
    esac
done

if [ -z "$USB_CARD" ]; then
    echo "ALSA: USB zvuková karta nenalezena — default zůstane systémový" >&2
fi
if [ -z "$BUILTIN_CARD" ]; then
    echo "ALSA: vestavěný jack Raspberry Pi nenalezen" >&2
fi

USB_PCM=""
BUILTIN_PCM=""
[ -n "$USB_CARD" ] && USB_PCM="$(card_pcm "$USB_CARD")"
[ -n "$BUILTIN_CARD" ] && BUILTIN_PCM="$(card_pcm "$BUILTIN_CARD")"

{
    echo "# generated by box-alsa-setup.sh — zvuková zařízení podle typu"
    echo "# pcm.usb      = USB zvuková karta boxu (AXAGON ADA-17), živí zesilovač"
    echo "# pcm.builtin  = vestavěný jack Raspberry Pi (bcm2835 Headphones)"
    echo "# karty jsou pojmenované (hw:CARD=...), ne číslované — přehození USB"
    echo "# portu nesmí přenastavit zvuk jinam."
    echo "# type plug převádí mono samply na stereo; type hw má jen 2 kanály."
    if [ -n "$BUILTIN_PCM" ]; then
        echo "pcm.builtin { type plug; slave.pcm \"$BUILTIN_PCM\" }"
    fi
    if [ -n "$USB_PCM" ]; then
        echo "pcm.usb { type plug; slave.pcm \"$USB_PCM\" }"
        echo "pcm.!default { type plug; slave.pcm usb }"
        echo "ctl.!default { type hw; card $USB_CARD }"
    fi
} > "$OUT"

echo "ALSA: usb=card$USB_CARD builtin=card$BUILTIN_CARD -> $OUT"
grep -v '^#' "$OUT" | tr '\n' ' ' || true
echo
