#!/bin/bash
# box-network.sh — statická adresa boxu v Raspberry Pi OS (NetworkManager).
#
#   usage: sudo ./box-network.sh <BOX>          # A nebo B
#          BOX_IP=192.168.8.103 BOX_WIFI_SSID=... sudo ./box-network.sh B
#
# Proč NetworkManager a ne dhcpcd: RPi OS od 2023 vede síť přes NetworkManager
# (v /etc/NetworkManager/system-connections/), takže /etc/dhcpcd.conf box nikdy
# nečte. Statická adresa je proto keyfile, ne řádek v konfiguraci daemona.
#
# Klíčové nastavení, které musí být v keyfilu správně:
#   * mode 0600 a vlastník root — NetworkManager odmítne keyfile s jinými
#     právy (kvůli WiFi heslu) a profil se tiše nezapojí.
#   * ipv4.method=manual — "auto" by nechalo DHCP přepsat adresu, pokud by jí
#     síť nabídla jinou.
#   * wifi.band=2.4 GHz? nepíšeme: Solight tlačítka jdou na 433 MHz, které je
#     mimo WiFi pásmo, a 5 GHz box nepotřebuje.
#
#   ABC38_NET_ROOT   default /     (kořen, do nějž se zapisuje)
#   BOX_IP           default 192.168.8.103 pro B, 192.168.8.104 pro A
#                    (dva boxy v jedné síti musí mít různé adresy; .102
#                    patří notebooku, ze kterého se image připravuje)
#   BOX_PREFIX       default 24
#   BOX_GATEWAY      default 192.168.8.1
#   BOX_DNS          default 192.168.8.1 (prázdné = bez DNS, box jen v lokální síti)
#   BOX_IFACE        default wlan0 když je zadané SSID, jinak eth0
#   BOX_WIFI_SSID    prázdné = WiFi profil nevytvářet
#   BOX_WIFI_PSK     WPA2 heslo; prázdné = otevřená síť
#   BOX_WIFI_HIDDEN  1 = skrytá síť
#   BOX_CONN_NAME    default "box-<BOX>"

set -e

ROOT="${ABC38_NET_ROOT:-/}"
CONN_DIR="$ROOT/etc/NetworkManager/system-connections"
SUFFIX="${CONN_NAME_SUFFIX:-nmconnection}"

BOX="${1:-B}"
case "$BOX" in
    A|B) ;;
    *) echo "ERROR: box must be A or B" >&2; exit 1 ;;
esac

case "$BOX" in
    A) DEFAULT_IP=192.168.8.104 ;;
    B) DEFAULT_IP=192.168.8.103 ;;
esac
IP="${BOX_IP:-$DEFAULT_IP}"
PREFIX="${BOX_PREFIX:-24}"
GATEWAY="${BOX_GATEWAY:-192.168.8.1}"
DNS="${BOX_DNS-192.168.8.1}"
SSID="${BOX_WIFI_SSID:-}"
PSK="${BOX_WIFI_PSK:-}"
HIDDEN="${BOX_WIFI_HIDDEN:-0}"
[ -n "$BOX_IFACE" ] && IFACE="$BOX_IFACE" || { [ -n "$SSID" ] && IFACE=wlan0 || IFACE=eth0; }
CONN_NAME="${BOX_CONN_NAME:-box-$BOX}"
OUT="$CONN_DIR/$CONN_NAME.$SUFFIX"

if ! printf '%s' "$IP" | grep -qE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
    echo "ERROR: BOX_IP is not an IPv4 address: $IP" >&2
    exit 1
fi

mkdir -p "$CONN_DIR"

{
    echo "# generated by box-network.sh — Box $BOX"
    echo "# statická adresa, aby na box nebylo potřeba hledat DHCP"
    if [ -n "$SSID" ]; then
        echo "[connection]"
        echo "id=$CONN_NAME"
        echo "uuid=$(python3 -c 'import uuid;print(uuid.uuid5(uuid.NAMESPACE_DNS,"box-'$BOX'"))' 2>/dev/null \
              || cat /proc/sys/kernel/random/uuid)"
        echo "type=wifi"
        echo "interface-name=$IFACE"
        echo "autoconnect=true"
        echo "autoconnect-retries=0"
        echo ""
        echo "[wifi]"
        echo "mode=infrastructure"
        echo "ssid=$SSID"
        echo "hidden=$HIDDEN"
        echo ""
        if [ -n "$PSK" ]; then
            echo "[wifi-security]"
            echo "key-mgmt=wpa-psk"
            echo "psk=$PSK"
            echo ""
        fi
    else
        echo "[connection]"
        echo "id=$CONN_NAME"
        echo "uuid=$(python3 -c 'import uuid;print(uuid.uuid5(uuid.NAMESPACE_DNS,"box-'$BOX'"))' 2>/dev/null \
              || cat /proc/sys/kernel/random/uuid)"
        echo "type=ethernet"
        echo "interface-name=$IFACE"
        echo "autoconnect=true"
        echo ""
        echo "[ethernet]"
        echo ""
    fi
    echo "[ipv4]"
    echo "method=manual"
    echo "addresses=$IP/$PREFIX"
    if [ -n "$GATEWAY" ]; then
        echo "gateway=$GATEWAY"
    fi
    if [ -n "$DNS" ]; then
        echo "dns=$DNS;"
    fi
    echo "never-default=false"
    echo ""
    echo "[ipv6]"
    echo "method=auto"
    echo ""
    echo "[proxy]"
} > "$OUT"

chmod 600 "$OUT"

echo "network: Box $BOX -> $CONN_NAME ($IFACE, $IP/$PREFIX, gw ${GATEWAY:-none})"
echo "  keyfile $OUT (600)"
